### ISSUE TITLE
Upper Hand combat order power 

### ISSUE THREAD

**Issue by CBroz1** [DeckofAdventures/TheGame#129]
This is essentially "If you get your Agility high enough, you get upper hand on combat TC for free". This avoids applying mods to turn order. [Related discussion](https://github.com/DeckofAdventures/TheGame/pull/127#discussion_r955476823)
```yaml
Quick Draw:
    Category: Combat
    Subcategory:  Control
    Type: Passive
    XP Cost: 0
    PP Cost: 0
    Prereq Skill: AGL > 2
    Tags: Combat
    Description: Reflexes so quick, you're always at the ready.
    Mechanic: When drawing a TC for combat, draw with Upper Hand.
```
