### ISSUE TITLE
Discard Mechanic revisions

### ISSUE THREAD

**Issue by CBroz1** [DeckofAdventures/TheGame#78]
1. Renaming to Burn Mechanic would highlight the nature of these discard abilities
2. To extend all to include non-combat effects
   1. Aggro to become FP power. Swap for intimidation?
   2. Thwart swap for information gathering?

**Comment by LockerM** [comment]
**Proposed Naming: Discard Actions**

Burn might be too specific to other card games, whereas Discard is general and more accessible. 

**Proposed testing parameters**

Let's keep Discard Actions by Role as previously established, and make it a Discard 4 for Lower/Upper (1) and then Discard 8 for (2). Watching a player in playtesting decide to take two rounds in a row using the Upper (1) meant he burned 1/5 of his stamina in just two turns, so I think this will need to be tested and evaluated from more player feedback before we dramatically retool it. Let's keep Caster as self - Upper Hand (1) and Support as other - Upper Hand (1) and do Martial and Defender as in-combat only reverting to Original proposed Discard Actions (formerly Primary Suit).

**Comment by CBroz1** [comment]
@LockerM - Yes, let's rename to Discard Actions.
1. 2:1 felt like the right ratio to me. What do you think?
2. Have we concluded these are combat-only? 
   - If so, Lend Aid (as pass-card) still overlaps. Maybe that's ok?
   - I'd prefer RP or combat, but I'm not what to offer Martial or Defender. A different passive? Only 2 options, available to all?
3. Should they appear on char sheets on Powers to be clearly visible at a glance?

**Comment by LockerM** [comment]
1. I agree with 2:1 as the initial and we can beta-test or focus group 4:1 instead once we have more play time with the discard mechanics at 2:1 

2. Combat only makes sense to me for now given that I don't find it likely for out-of-combat to be that draining on stamina, which is the main goal/mechanic of the discard actions. If we come up with more complex Discard Actions down the road that affect RP/Social encounters we can implement them at a later stage, but for now it would make sense to me for each Role to have a main Discard Action they use in combat that helps emphasize their Role in the party. Outside of combat the distinction between a Support and a Caster or a Martial and a Defender isn't as distinct because that will be shaped more by the non-role powers they take and the approach to stats/RP on an individual Player basis. 

3. I think on character sheets there can be a single line for Discard Actions with the name of the Discard Action, a brief description of the effect, and the maximum amount of cards that can be discarded in a single Discard Action for the level they're at.

**Comment by LockerM** [comment]
Could we implement 1 or 2 Discard Actions that *all* characters get access to, and can be more useful in RP or social/exploration scenarios? This way we have a Role-specific Discard Action that would be included in each player's Character Sheet as their unique Discard Action, but then make Discard Actions for RP scenarios and out of combat use.

Proposed version of Discard Mechanics: 
- Discard 2 cards before making an Investigation or Detection check. Draw that check with Upper Hand. 
- Discard 2 cards before making a Bluffing or Performance check. Draw that check with Upper Hand. 

*Note* - we could make these out of combat discard mechanics more punishing to limit their use, by either limiting use to X times per rest, or by making them require 4:1 instead of 2:1.

**Comment by LockerM** [comment]
Two possibilities where Discard Actions are Powers: 

1. Everyone has exactly 1 Discard Action, assumed to be the one exclusive to your Role but none are specific to roles
2. We make the premades and they each happen to have a Deck Action, but no one *has* to take a Deck Action, and anyone could, and you have a character who specializes in Deck Actions as the subset of Powers they take 

*Discard Mechanics/Deck Actions are always Minor Actions*

**Comment by LockerM** [comment]
Note from @D-D-2 - Having role-specific deck actions helps people when they select their Role of 'what they get'

**Comment by LockerM** [comment]
Proposed revision to a Support discard action rather than a repeat of lend aid (which is now more powerful anyway since it only costs 1 card):

**Infuse**: Add effectiveness to your next Healing or Shielding effect. Discard 2 cards to add +1 or discard 4 cards to add +2. 

This would make Shield and Heal way more powerful, so I would also propose making each Power only cost 1 PP and only add 1 AP/HP pre-infuse. Then at higher levels we can unlock Shield, Major and Heal, Major that go up to 3 AP/HP with the ability at higher levels to discard more cards to get up to 5/6 AP/HP (makes scaling easier and keeps the discard action balanced while in keeping with the role).

**Comment by LockerM** [comment]
Proposed revision to Caster discard action to prevent their one being the only effective out of combat one while simultaneously solving for a Caster playtester wanting something similar to Charge Attack. 

**Amplify**: Your next Power that deals damage gains additional damage. Discard 2 cards for +1 damage or 4 cards for +2 damage. 

_---_

The above would be a good example where 4 and 8 cards might end up making more sense for some discard actions, or reconfiguring the way Cards draining feels for players to balance risk/reward on these to avoid a player spamming it (or limiting number of discard actions - possibly tying them to another resource akin to Rest Cards or some type of level bonus uses per rest, etc).

**Comment by LockerM** [comment]
Opportunity for us to evaluate an RP Specific set of Discard Actions. Potentially having a universal set of discard actions (or singular action) that is used out of combat by all characters in DofA regardless of Role.

Potential Options (not tied to or convinced any of the below are the right solution yet)
1. could we modify "Lucky" to be - on a Suited Miss you can discard 2 cards and redraw the check. 
2. Choose a Skill (Can be your primary Skill). When making checks with this Skill you can use your Discard Action (N) to give yourself Upper Hand (N) on that check. 
3. When you fail a Save, you can discard 2 cards and redraw the Save. (Potentially discard 4th and gain Upper Hand on the Save) - *this has some overlap with Fate Cards so not guaranteed*

**Comment by CBroz1** [comment]
For the yaml below, assume all Minor type, with 0 XP at Prereq Level 2 and Discard category (with the limit 1 stimulation).

I don't think we're going to find 4 discard mechanic options that balanced whether used in or out of combat surface. We can address this by ...
1. Making the above `Help` and  `Thwart` core mechanics that are always accessible and using `Infuse` and `Amplify` as replacements. This comes at the cost of a low learning-curve ruleset.
2. Making 4 discard mechanics, but some offer two mechanics, one in and one out of combat.
3. Making 4 (or 6) combat-only discard mechanics. Deck actions can play a similar role for out-of-combat discard features.

Adding in/out combat variants for only 4 options (see 2 above)
```yaml
Aggro:
    Description: Protecting your friends means taking the big hits and drawing focus.
    Mechanic: Discard N cards to grant one of the following effects for all creatures you choose within 2 spaces.
        - In combat, creatures make their next Check to attack targets you at Lower Hand (N/2). 
        - Out of combat, creatures make their next 2 Checks at Lower Hand (N/2).

Help:
    Description: You're there just when your friends need you.
    Mechanic: Discard N cards to...
        - In combat, add +(N/2) HP or AP to the next Power you use that already grants HP or AP.
        - Out of combat, grant one creature within 6 spaces Upper Hand (N/2) their next 2 Checks.

Thwart:
    Description: You have a few tricks up your sleeve for drawing the enemy's attention.
    Mechanic: Discard N cards to ...
        - In combat, add +(N/2) damage to the next Power you use that causes damage. This effect expires on a Miss.
        - Out of combat, cause a creature within 6 spaces to make their next 2 Checks at Lower Hand (N/2).

Intensify:
    Description: An explosive burst may mean running out of gas.
    Mechanic: On your next check, discard cards until you reach a Major Success. Standard Successes are treated as Misses. You can choose to end this effect early.
```

Adding `Infuse` and `Amplify` to the existing set (see 3 above):
```yaml
Aggro:
    Description: Protecting your friends means taking the big hits.
    Mechanic: Discard N cards to force all creatures within 2 spaces to make their next Check to attack targets besides the triggering Dealer at Lower Hand (N/2)

Intensify:
    Description: An explosive attack might mean running out of gas.
    Mechanic: On your next Attack, discard cards until you reach a Major Success. Standard Successes are treated as Misses. You can choose to end this effect early.

Help:
    Description: You're there just when your friends need you.
    Mechanic: In Combat, discard N cards to grant an ally within 6 spaces Upper Hand (N/2) on all Checks for their next turn

Thwart:
    Description: You have a few tricks up your sleeve for drawing the enemy's attention.
    Mechanic: Discard N cards and cause an enemy within 6 spaces to make all Checks at Lower Hand (N/2) until the start of the triggering Dealer's next turn

Infuse:
    Description: You pour yourself into helping others.
    Mechanic: Discard N cards to add +(N/2) HP or AP to the next Power you use that already grants HP or AP.

Amplify:
    Description: You pour yourself into destruction.
    Mechanic: Discard N cards to add +(N/2) damage to the next Power you use that causes damage. This effect expires on a Miss.
```
